version: '3'

services:
  build: 
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes: 
      - static_volume:/home/app/static

  web: 
    build: .
    expose:
      - 5000

  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/home/app/static
    ports:
      - 1337:80
    depends_on:
      - web
      - build

volumes: 
  static_volume:
