version: '3'

services:
  web: 
    build: .
    expose:
      - 5000
    volumes: 
      - static_volume:/build/app/static

  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/build/app/static
    ports:
      - 1337:80
    depends_on:
      - web
    
volumes: 
  static_volume:
